name: documentação
description: Issue para documentação
labels: ["documentation"]
body:
  - type: textarea
    id: Descricao
    attributes:
      label: Descrição
      description: Descreva o que precisa ser feito. Se possível, adicione imagens ou links para ajudar a entender o problema.
    validations:
      required: true
  - type: checkboxes
    id: Tarefas
    attributes:
      label: Tarefas
      options:
        - label: Documentar em 3.X.X.
        - labal: Seguir [template de documentação](https://github.com/UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_03/blob/main/.github/TEMPLATE_DOC.md)
        - labal: Colocar na issue a gravação da realização.
  - type: checkboxes
    id: criterios
    attributes:
      label: Critérios de aceitação
      options:
        - label: Titulo enumerado
        - labal: Ortografia correta
        - labal: Link nos textos para as referencias 
        - labal: Bibliografia está presente e segue o padrão ABNT
        - labal: Versionamento padronizado
        - labal: Títulos e citações em figuras, tabelas e videos seguem o padão ANBT
        - labal: Citações diferem autores de fonte
  - type: textarea
    id: Observacoes
    attributes:
      label: Observações
      description: Adicione informações adicionais que julgar necessário.
    validations:
      required: false